/* Generated by scripts/build-manifest.mjs from qenivo/src/qenivo/models/industry.py. */
import type { LibraryModel } from "./library.js";

export const library: LibraryModel[] = [
  {
    "name": "economic_dispatch",
    "sector": "power system dispatch",
    "problemClass": "QP",
    "formulation": "quadratic fuel cost, ramping, reserve (Wood & Wollenberg, ch. 3)",
    "summary": "Multi-period economic dispatch, a convex QP: min sum a P^2 + b P subject to demand, spinning reserve, unit limits and ramp limits.",
    "detail": "Multi-period economic dispatch, a convex QP: min sum a P^2 + b P subject to demand, spinning reserve, unit limits and ramp limits.",
    "parameters": [
      {
        "name": "units",
        "default": "10"
      },
      {
        "name": "periods",
        "default": "24"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model economic_dispatch -p units=10 -p periods=24 -p seed=0 -o economic_dispatch.mps"
  },
  {
    "name": "unit_commitment",
    "sector": "power system dispatch",
    "problemClass": "MILP",
    "formulation": "on/off, start-up cost, min up time (Carrion & Arroyo 2006, compact form)",
    "summary": "Unit commitment MILP: binary on/off u, start-up v, min up time, piecewise-free linear cost.",
    "detail": "Unit commitment MILP: binary on/off u, start-up v, min up time, piecewise-free linear cost.",
    "parameters": [
      {
        "name": "units",
        "default": "10"
      },
      {
        "name": "periods",
        "default": "24"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model unit_commitment -p units=10 -p periods=24 -p seed=0 -o unit_commitment.mps"
  },
  {
    "name": "transportation",
    "sector": "transportation",
    "problemClass": "LP",
    "formulation": "Hitchcock transportation problem",
    "summary": "Transportation LP: ship from supply points to demand points at least distance cost.",
    "detail": "Transportation LP: ship from supply points to demand points at least distance cost.",
    "parameters": [
      {
        "name": "sources",
        "default": "50"
      },
      {
        "name": "sinks",
        "default": "200"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model transportation -p sources=50 -p sinks=200 -p seed=0 -o transportation.mps"
  },
  {
    "name": "facility_location",
    "sector": "supply chain management",
    "problemClass": "MILP",
    "formulation": "capacitated facility location (Cornuejols, Sridharan & Thizy 1991)",
    "summary": "Capacitated facility location MILP with the strong linking constraints x_ij <= d_j y_i.",
    "detail": "Capacitated facility location MILP with the strong linking constraints x_ij <= d_j y_i.",
    "parameters": [
      {
        "name": "facilities",
        "default": "20"
      },
      {
        "name": "customers",
        "default": "80"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model facility_location -p facilities=20 -p customers=80 -p seed=0 -o facility_location.mps"
  },
  {
    "name": "lot_sizing",
    "sector": "production planning",
    "problemClass": "MILP",
    "formulation": "multi-item capacitated lot sizing with setups (Pochet & Wolsey 2006)",
    "summary": "Multi-item capacitated lot sizing: production x, stock s, setup y (binary).",
    "detail": "Multi-item capacitated lot sizing: production x, stock s, setup y (binary).",
    "parameters": [
      {
        "name": "items",
        "default": "6"
      },
      {
        "name": "periods",
        "default": "12"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model lot_sizing -p items=6 -p periods=12 -p seed=0 -o lot_sizing.mps"
  },
  {
    "name": "crude_blending",
    "sector": "crude blending",
    "problemClass": "LP",
    "formulation": "crude slate blend to sulphur / API / TAN specs",
    "summary": "Blend a crude slate for the distillation unit at minimum cost, within the unit's limits on sulphur, API gravity and total acid number, with availability limits per crude.",
    "detail": "Blend a crude slate for the distillation unit at minimum cost, within the unit's limits on sulphur, API gravity and total acid number, with availability limits per crude.",
    "parameters": [
      {
        "name": "crudes",
        "default": "12"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model crude_blending -p crudes=12 -p seed=0 -o crude_blending.mps"
  },
  {
    "name": "crude_scheduling",
    "sector": "refinery scheduling",
    "problemClass": "MILP",
    "formulation": "discrete-time crude unloading, tank inventory and CDU charging (after Lee, Pinto, Grossmann & Park 1996, linear variant)",
    "summary": "Discrete-time crude unloading and charging: vessels unload crude into tanks, one crude per tank at a time (binary), tanks feed the CDU at a fixed rate, and the CDU charge must meet blended sulphur limits. Costs: tank changeovers and inventory.",
    "detail": "Discrete-time crude unloading and charging: vessels unload crude into tanks, one crude per tank at a time (binary), tanks feed the CDU at a fixed rate, and the CDU charge must meet blended sulphur limits. Costs: tank changeovers and inventory.",
    "parameters": [
      {
        "name": "tanks",
        "default": "4"
      },
      {
        "name": "crudes",
        "default": "3"
      },
      {
        "name": "periods",
        "default": "12"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model crude_scheduling -p tanks=4 -p crudes=3 -p periods=12 -p seed=0 -o crude_scheduling.mps"
  },
  {
    "name": "multi_commodity_flow",
    "sector": "logistics",
    "problemClass": "LP",
    "formulation": "multi-commodity network flow with shared arc capacity",
    "summary": "Multi-commodity network flow LP: route several origin-destination demands over shared arcs.",
    "detail": "Multi-commodity network flow LP: route several origin-destination demands over shared arcs.",
    "parameters": [
      {
        "name": "nodes",
        "default": "30"
      },
      {
        "name": "commodities",
        "default": "8"
      },
      {
        "name": "seed",
        "default": "0"
      }
    ],
    "command": "qenivo model multi_commodity_flow -p nodes=30 -p commodities=8 -p seed=0 -o multi_commodity_flow.mps"
  }
];
