// Elimination tree, column counts and fundamental supernodes.
//
// The tree is built by the ancestor-compression walk in J. W. H. Liu, "The role of
// elimination trees in sparse factorization", SIAM J. Matrix Anal. Appl. 11 (1990).
// Column counts are the sizes of the nonzero patterns generated by the subtree-union
// rule (D. J. Rose, R. E. Tarjan and G. S. Lueker, SIAM J. Comput. 5 (1976)).
// A run of columns is one fundamental supernode when each is the parent of the
// previous and the patterns differ by exactly that column (J. W. H. Liu, E. G. Ng
// and B. W. Peyton, SIAM J. Matrix Anal. Appl. 14 (1993)). The pattern test is
// checked explicitly so a count tie cannot glue unlike columns.

#include "ipm_internal.hpp"

#include <algorithm>
#include <cstdint>
#include <unordered_map>
#include <utility>
#include <vector>

namespace qenivo {

Assembled assemble_lower(int n, const int* colptr, const int* rowidx, const double* values, const int* perm) {
    Assembled out;
    out.n = n;
    if (n <= 0) {
        out.colptr.assign(1, 0);
        out.scale = 1.0;
        return out;
    }
    std::vector<int> inv(n);
    if (perm == nullptr) {
        for (int i = 0; i < n; ++i) {
            inv[i] = i;
        }
    } else {
        for (int i = 0; i < n; ++i) {
            inv[perm[i]] = i;
        }
    }
    std::unordered_map<uint64_t, double> lower;
    std::unordered_map<uint64_t, double> upper_val;
    auto key_of = [](int col, int row) -> uint64_t {
        return ((uint64_t)(uint32_t)col << 32) | (uint32_t)row;
    };
    if (colptr != nullptr && rowidx != nullptr) {
        for (int j = 0; j < n; ++j) {
            for (int p = colptr[j]; p < colptr[j + 1]; ++p) {
                int i = rowidx[p];
                if (i < 0 || i >= n) {
                    continue;
                }
                double v = values == nullptr ? 1.0 : values[p];
                if (v == 0.0 || v != v) {
                    continue;
                }
                if (i >= j) {
                    lower[key_of(j, i)] += v;
                } else {
                    uint64_t k = key_of(i, j);
                    upper_val[k] += v;
                }
            }
        }
    }
    std::vector<std::vector<std::pair<int, double>>> cols(n);
    auto place = [&](int col, int row, double v) {
        int pc = inv[col];
        int pr = inv[row];
        if (pr < pc) {
            std::swap(pr, pc);
        }
        cols[pc].push_back({pr, v});
    };
    for (const auto& kv : lower) {
        int col = (int)(kv.first >> 32);
        int row = (int)(kv.first & 0xffffffffu);
        place(col, row, kv.second);
    }
    for (const auto& kv : upper_val) {
        if (lower.find(kv.first) != lower.end()) {
            continue;
        }
        int col = (int)(kv.first >> 32);
        int row = (int)(kv.first & 0xffffffffu);
        place(col, row, kv.second);
    }
    out.diag.assign(n, 0.0);
    out.strict.assign(n, {});
    out.colptr.assign(n + 1, 0);
    std::vector<int> rows;
    std::vector<double> vals;
    for (int j = 0; j < n; ++j) {
        auto& col = cols[j];
        std::sort(col.begin(), col.end(), [](const auto& a, const auto& b) { return a.first < b.first; });
        out.colptr[j] = (int)rows.size();
        for (size_t p = 0; p < col.size();) {
            int r = col[p].first;
            double s = 0.0;
            while (p < col.size() && col[p].first == r) {
                s += col[p].second;
                ++p;
            }
            if (s == 0.0 || s != s) {
                continue;
            }
            rows.push_back(r);
            vals.push_back(s);
            if (r == j) {
                out.diag[j] = s;
            } else if (r > j) {
                out.strict[j].push_back(r);
            }
        }
    }
    out.colptr[n] = (int)rows.size();
    out.rowidx.swap(rows);
    out.values.swap(vals);
    out.scale = 1.0;
    for (double d : out.diag) {
        double a = d < 0 ? -d : d;
        if (a > out.scale) {
            out.scale = a;
        }
    }
    return out;
}

namespace {

bool extends_supernode(const std::vector<int>& previous, const std::vector<int>& current, int column) {
    if (previous.size() != current.size() + 1) {
        return false;
    }
    size_t q = 0;
    bool saw = false;
    for (int row : previous) {
        if (q < current.size() && row == current[q]) {
            ++q;
        } else if (row == column && !saw) {
            saw = true;
        } else {
            return false;
        }
    }
    return saw && q == current.size();
}

}  // namespace

Symbolic symbolic_factor(const Assembled& lower) {
    const int n = lower.n;
    Symbolic sym;
    sym.n = n;
    sym.parent.assign(n, -1);
    sym.colcount.assign(n, 1);
    sym.pattern.assign(n, {});
    sym.sn_id.assign(n, 0);
    if (n == 0) {
        sym.sn_start.push_back(0);
        return sym;
    }
    std::vector<std::vector<int>> upper(n);
    for (int j = 0; j < n; ++j) {
        for (int i : lower.strict[j]) {
            if (i > j && i < n) {
                upper[i].push_back(j);
            }
        }
    }
    std::vector<int> ancestor(n, -1);
    for (int j = 0; j < n; ++j) {
        for (int i : upper[j]) {
            int r = i;
            while (ancestor[r] != -1 && ancestor[r] != j) {
                int next = ancestor[r];
                ancestor[r] = j;
                r = next;
            }
            if (ancestor[r] == -1) {
                ancestor[r] = j;
                sym.parent[r] = j;
            }
        }
    }
    std::vector<std::vector<int>> children(n);
    for (int j = 0; j < n; ++j) {
        if (sym.parent[j] >= 0) {
            children[sym.parent[j]].push_back(j);
        }
    }
    for (int j = 0; j < n; ++j) {
        std::vector<int> acc = lower.strict[j];
        for (int c : children[j]) {
            for (int row : sym.pattern[c]) {
                if (row > j) {
                    acc.push_back(row);
                }
            }
        }
        std::sort(acc.begin(), acc.end());
        acc.erase(std::unique(acc.begin(), acc.end()), acc.end());
        acc.erase(std::remove(acc.begin(), acc.end(), j), acc.end());
        sym.pattern[j] = std::move(acc);
        sym.colcount[j] = (int)sym.pattern[j].size() + 1;
    }
    sym.sn_start.push_back(0);
    if (n > 0) {
        sym.sn_id[0] = 0;
    }
    for (int j = 1; j < n; ++j) {
        bool merge = sym.parent[j - 1] == j && sym.colcount[j - 1] == sym.colcount[j] + 1 &&
                     extends_supernode(sym.pattern[j - 1], sym.pattern[j], j);
        if (merge) {
            sym.sn_id[j] = sym.sn_id[j - 1];
        } else {
            sym.sn_id[j] = sym.sn_id[j - 1] + 1;
            sym.sn_start.push_back(j);
        }
    }
    sym.sn_start.push_back(n);
    const int ns = (int)sym.sn_start.size() - 1;
    sym.sn_parent.assign(ns, -1);
    for (int s = 0; s < ns; ++s) {
        int last = sym.sn_start[s + 1] - 1;
        int p = sym.parent[last];
        sym.sn_parent[s] = (p >= 0 && p < n) ? sym.sn_id[p] : -1;
    }
    return sym;
}

}  // namespace qenivo
